# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"

  ip = File.read('vagrant.txt').gsub(/\s+$/, '').strip
  config.vm.network "private_network", ip: ip
end
